on:
  workflow_call:

name: revdep

jobs:

  check:

    runs-on: ubuntu-latest

    name: ${{ matrix.config.pkg }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {pkg: 'blockr.ai'}

    env:
      GITHUB_PAT: ${{ secrets.BLOCKR_PAT }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
        with:
          path: core

      - uses: actions/checkout@v4
        with:
          repository: cynkra/${{ matrix.config.pkg }}
          token: ${{ secrets.BLOCKR_PAT }}
          path: dep

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            local::../dep
          working-directory: core

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: dep
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
